[tool.poetry]
name = "nebula"
version = "0.1.0"
description = "A synthetic data generator pipeline"
authors = ["TimothePearce <timothe.pearce@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = "^6.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
nebula = "nebula.cli:main"
